#**Name: NaveenKumar - Team Lead**

# **Roll No: 412419104023**

# **Batch No: B5-5M1E**



# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
data = s.split()
data

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
# dt = "The diameter of {} is {} kilometer."
print("The diameter of {} is {} kilometer.".format(planet, diameter))

The diameter of Earth is 12742 kilometer.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
ar = np.zeros(10)
ar

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
arra = np.arange(20,35,2)
arra

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
array = np.arange(0, 9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.concatenate((a,b), axis = 0)
c

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
doto = [['XXX', 'CSE', 85],['YYY', 'CSE', 95], ['ZZZ', 'CSE', 97]]
do = pd.DataFrame(doto, columns=['Name', 'DEPT', 'Mark'])

do

Name DEPT  Mark
0  XXX  CSE    85
1  YYY  CSE    95
2  ZZZ  CSE    97

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
date = pd.date_range("1/1/2023", freq="D", periods=41)
date

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pd.Series(range(41), index=pd.date_range("1/1/2023", freq="D", periods=41))


2023-01-01     0
2023-01-02     1
2023-01-03     2
2023-01-04     3
2023-01-05     4
2023-01-06     5
2023-01-07     6
2023-01-08     7
2023-01-09     8
2023-01-10     9
2023-01-11    10
2023-01-12    11
2023-01-13    12
2023-01-14    13
2023-01-15    14
2023-01-16    15
2023-01-17    16
2023-01-18    17
2023-01-19    18
2023-01-20    19
2023-01-21    20
2023-01-22    21
2023-01-23    22
2023-01-24    23
2023-01-25    24
2023-01-26    25
2023-01-27    26
2023-01-28    27
2023-01-29    28
2023-01-30    29
2023-01-31    30
2023-02-01    31
2023-02-02    32
2023-02-03    33
2023-02-04    34
2023-02-05    35
2023-02-06    36
2023-02-07    37
2023-02-08    38
2023-02-09    39
2023-02-10    40
Freq: D, dtype: int64

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
ls = pd.DataFrame(lists, columns=['Number', 'Name', 'Mark'])
ls

Number Name  Mark
0       1  aaa    22
1       2  bbb    25
2       3  ccc    24